export const AP_DISTRICT_MAP_IDS = {
  SRI: 'Srikakulam',
  VIZ: 'Vizianagaram',
  VIS: 'Visakhapatnam',
  EGA: 'East Godavari',
  WGE: 'West Godavari',
  KRI: 'Krishna',
  GUN: 'Guntur',
  KUR: 'Kurnool',
  PRA: 'Prakasam',
  YSR: 'YSR (Kadapa)',
  SPS: 'Sri Potti Sriramulu Nellore',
  ANA: 'Anantapuramu',
  CHI: 'Chittoor',
  TIR: 'Tirupati',
  ANN: 'Annamayya',
  SSS: 'Sri Sathya Sai',
  BAP: 'Bapatla',
  PMA: 'Parvathipuram Manyam',
  ELU: 'Eluru',
  ASR: 'Alluri Sitharama Raju',
  KON: 'Konaseema',
  KAK: 'Kakinada',
  ANK: 'Anakapalli',
  NAN: 'Nandyal',
  NTR: 'NTR',
  PAL: 'Palnadu'
};

export const AP_DISTRICT_MAP_ID_LIST = Object.keys(AP_DISTRICT_MAP_IDS);

/** Database district names → SVG path IDs (Explore AP map) */
export const AP_DISTRICT_DB_NAME_TO_MAP_ID = {
  'Alluri Sitharama Raju': 'ASR',
  'Anakapalli': 'ANK',
  'Anantapur': 'ANA',
  'Annamayya': 'ANN',
  'Bapatla': 'BAP',
  'Chittoor': 'CHI',
  'Dr. B. R. Ambedkar Konaseema': 'KON',
  'East Godavari': 'EGA',
  'Eluru': 'ELU',
  'Guntur': 'GUN',
  'Kakinada': 'KAK',
  'Krishna': 'KRI',
  'Kurnool': 'KUR',
  'Nandyal': 'NAN',
  'NTR': 'NTR',
  'Palnadu': 'PAL',
  'Parvathipuram Manyam': 'PMA',
  'Prakasam': 'PRA',
  'Sri Balaji (Tirupati)': 'TIR',
  'Sri Potti Sriramulu Nellore': 'SPS',
  'Sri Sathya Sai': 'SSS',
  'Srikakulam': 'SRI',
  'Visakhapatnam': 'VIS',
  'Vizianagaram': 'VIZ',
  'West Godavari': 'WGE',
  'YSR Kadapa': 'YSR'
};
